import fs from 'node:fs/promises';
import process from 'node:process';
const cfg=JSON.parse(await fs.readFile(process.env.OEE_EDGE_CONFIG||'config.json','utf8'));
const worker=(process.env.OEE_WORKER_URL||cfg.worker_url||'').replace(/\/$/,'');
const edgeKey=process.env.OEE_EDGE_KEY||'';
if(!worker||!edgeKey)throw Error('OEE_WORKER_URL/worker_url dan OEE_EDGE_KEY wajib diisi.');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const cache=new Map(),connections=new Map();
const now=()=>new Date().toISOString();
async function post(path,payload){const r=await fetch(worker+path,{method:'POST',headers:{'Content-Type':'application/json','X-Edge-Key':edgeKey},body:JSON.stringify(payload)});if(!r.ok)throw Error(path+' HTTP '+r.status+' '+await r.text());return r.json();}
function deriveState(v,m){if(v.alarm&&(m.state_map?.alarm_true||'UPDT'))return m.state_map?.alarm_true||'UPDT';return v.running?(m.state_map?.running_true||'RUNNING'):(m.state_map?.running_false||'IDLE');}
async function opcRead(m){let c=connections.get(m.code);if(!c){const {OPCUAClient,AttributeIds}=await import('node-opcua-client');const client=OPCUAClient.create({endpointMustExist:false,connectionStrategy:{initialDelay:250,maxRetry:2,maxDelay:2000}});await client.connect(m.endpoint);const session=await client.createSession();c={client,session,AttributeIds};connections.set(m.code,c);}const keys=Object.keys(m.tags||{}),nodes=keys.map(k=>({nodeId:m.tags[k],attributeId:c.AttributeIds.Value})),values=await c.session.read(nodes);return Object.fromEntries(keys.map((k,i)=>[k,values[i]?.value?.value]));}
async function modbusRead(m){let c=connections.get(m.code);if(!c){const Modbus=(await import('modbus-serial')).default;c=new Modbus();await c.connectTCP(m.host,{port:m.port||502});c.setID(m.unit_id||1);connections.set(m.code,c);}const out={};for(const [k,t] of Object.entries(m.tags||{})){let r;if(t.type==='coil')r=await c.readCoils(t.address,t.length||1);else if(t.type==='input')r=await c.readInputRegisters(t.address,t.length||1);else r=await c.readHoldingRegisters(t.address,t.length||1);if(t.type==='coil')out[k]=!!r.data[0];else if(t.format==='uint32'){const hi=Number(r.data[0]||0),lo=Number(r.data[1]||0);out[k]=hi*65536+lo;}else out[k]=Number(r.data[0]||0);}return out;}
async function readMachine(m){if(m.protocol==='opcua')return opcRead(m);if(m.protocol==='modbus-tcp')return modbusRead(m);if(m.protocol==='http-json'){const r=await fetch(m.url);if(!r.ok)throw Error('HTTP '+r.status);return r.json();}throw Error('Protocol tidak didukung: '+m.protocol);}
async function sampleMachine(m){try{const v=await readMachine(m),state=deriveState(v,m),prev=cache.get(m.code)||{},ts=now(),changed=prev.state!==state||String(prev.alarm??'')!==String(v.alarm??'');cache.set(m.code,{...v,state,last:Date.now(),lastSnapshot:prev.lastSnapshot||0});if(changed){await post('/api/edge/events',{events:[{machine_code:m.code,name:m.name,state,counter:Number(v.counter||0),speed:Number(v.speed||0),alarm:v.alarm||null,event_type:prev.state?'state':'startup',ts}]});}const c=cache.get(m.code);if(Date.now()-(c.lastSnapshot||0)>Number(cfg.snapshot_ms||60000)){await post('/api/edge/events',{events:[{machine_code:m.code,name:m.name,state,counter:Number(v.counter||0),speed:Number(v.speed||0),alarm:v.alarm||null,event_type:'snapshot',ts}]});c.lastSnapshot=Date.now();cache.set(m.code,c);}console.log(ts,m.code,state,'counter',v.counter??0,'speed',v.speed??0);}catch(e){console.error(now(),m.code,e.message);const old=connections.get(m.code);if(old?.session)try{await old.session.close()}catch{}if(old?.client)try{await old.client.disconnect()}catch{}if(old?.close)try{old.close(()=>{})}catch{}connections.delete(m.code);}}
async function machineLoop(){const machines=(cfg.machines||[]).filter(x=>x.enabled);while(true){await Promise.allSettled(machines.map(sampleMachine));await sleep(Number(cfg.poll_ms||2000));}}
function getPath(o,p){return String(p||'').split('.').filter(Boolean).reduce((v,k)=>v==null?undefined:v[k],o)}
async function syncSystem(s){try{const r=await fetch(s.url,{headers:s.headers||{}});if(!r.ok)throw Error('HTTP '+r.status);const body=await r.json();let items=s.items_path?getPath(body,s.items_path):body;if(!Array.isArray(items))items=[items];const res=await post('/api/edge/sync',{system:s.system,target:s.target,items,mapping:s.mapping||{}});console.log(now(),s.system,s.target,res.accepted,'record');}catch(e){console.error(now(),s.system,e.message);}}
async function systemLoop(s){const wait=Math.max(60000,Number(s.interval_ms||300000));while(true){await syncSystem(s);await sleep(wait);}}
process.on('SIGINT',async()=>{for(const c of connections.values()){if(c.session)try{await c.session.close()}catch{}if(c.client)try{await c.client.disconnect()}catch{}}process.exit(0);});
console.log('OEE COLLABORACTION Edge Gateway aktif →',worker);
await Promise.all([machineLoop(),...(cfg.internal_systems||[]).filter(x=>x.enabled).map(systemLoop)]);
