const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('id-ID',{maximumFractionDigits:d}):'—';const pct=n=>typeof n==='number'?fmt(n*100,2)+'%':'—';
let base=window.OEE_CONFIG.apiBase||sessionStorage.getItem('oee-api')||'',token=sessionStorage.getItem('oee-token')||'',user,catalog,view='dashboard',activeSheet='',page=0,query='',rows=[],total=0;
const departments={PROD:'Produksi',QC:'Quality Control',MTC:'Maintenance',PPIC:'Planning & Konfirmasi',PDS:'Development',PROJECT:'Proyek & Master'};
const modules={confirmation:['Konfirmasi PPIC','PPIC'],planning:['Planning produksi','PPIC'],production:['Hasil produksi','PROD'],downtime:['PDT / UPDT & COJ','PROD'],quality:['Reject & QC','QC'],maintenance:['Corrective maintenance','MTC'],development:['Biaya & trial','PDS'],checklist:['Checklist persiapan','PROD'],logbook:['Logbook','PROD'],process:['Process performance','QC'],energy:['Energi','PROD'],master:['Master data','PROJECT'],project:['Action plan proyek','PROJECT']};
const can=(d,a)=>user?.role==='superadmin'||(user?.role==='admin'&&user.department===d&&user.permissions.includes(a));
const toast=t=>{$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',6500);};
async function api(path,method='GET',data){if(!base)throw Error('Isi alamat backend Cloudflare terlebih dahulu.');const r=await fetch(base.replace(/\/$/,'')+'/api'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});let v;try{v=await r.json();}catch{throw Error('Respons backend bukan JSON. Periksa alamat koneksi.');}if(!r.ok){if(r.status===401&&user){user=null;token='';sessionStorage.removeItem('oee-token');login();}throw Error(v.error||'Permintaan gagal');}return v;}
function dialog(title,content){modal.innerHTML=`<div class="dialoghead"><h2 style="margin:0">${esc(title)}</h2><button id="closeDialog" aria-label="Tutup">×</button></div><div class="dialogbody">${content}</div>`;$('#closeDialog').onclick=()=>modal.close();modal.showModal();}
