const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('id-ID',{maximumFractionDigits:d}):'—';const pct=n=>typeof n==='number'?fmt(n*100,2)+'%':'—';
const APP_NAME='OEE COLLABORACTION - BMJ PACKAGING OFFSET';
const APP_TAG='Intelligent Platform © 2026 IDJ';
const APP_SHORT='OEE COLLABORACTION';
let base=window.OEE_CONFIG.apiBase||'',token=sessionStorage.getItem('oee-token')||'',user,catalog,view='dashboard',activeSheet='',page=0,query='',rows=[],total=0;
const icon=(name,cls='')=>`<svg class="svg-icon ${cls}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><use href="assets/icons.svg#${/^[a-z]+$/.test(name)?name:'dashboard'}"></use></svg>`;
const departments={PROD:'Produksi',QC:'Quality Control',MTC:'Maintenance',PPIC:'Planning & Konfirmasi',PDS:'Development',PROJECT:'Proyek & Master'};
const modules={confirmation:['Konfirmasi PPIC','PPIC'],planning:['Planning produksi','PPIC'],production:['Hasil produksi','PROD'],downtime:['PDT / UPDT & COJ','PROD'],quality:['Reject & QC','QC'],maintenance:['Corrective maintenance','MTC'],development:['Biaya & trial','PDS'],checklist:['Checklist persiapan','PROD'],logbook:['Logbook','PROD'],process:['Process performance','QC'],energy:['Energi','PROD'],master:['Master data','PROJECT'],project:['Action plan proyek','PROJECT'],batch:['Output per batch','PROD']};
const permissionList=()=>Array.isArray(user?.permissions)?user.permissions:[];
const can=(d,a)=>user?.role==='superadmin'||(user?.role==='admin'&&user.department===d&&permissionList().includes(a));
const toast=t=>{$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',6500);};
async function api(path,method='GET',data){if(!base)throw Error('Backend Cloudflare belum terhubung.');const r=await fetch(base.replace(/\/$/,'')+'/api'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});let v;try{v=await r.json();}catch{throw Error('Respons backend bukan JSON.');}if(!r.ok){if(r.status===401&&user){user=null;token='';sessionStorage.removeItem('oee-token');login();}throw Error(v.error||'Permintaan gagal');}return v;}
let dialogReturnFocus=null;
function dialog(title,content){const opening=!modal.open;if(opening)dialogReturnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;modal.innerHTML=`<div class="dialoghead"><h2 id="modalTitle" style="margin:0">${esc(title)}</h2><button id="closeDialog" aria-label="Tutup dialog">×</button></div><div class="dialogbody">${content}</div>`;modal.setAttribute('aria-labelledby','modalTitle');$('#closeDialog').onclick=()=>modal.close();if(opening){modal.showModal();queueMicrotask(()=>{const target=modal.querySelector('[autofocus],.dialogbody input:not([disabled]),.dialogbody select:not([disabled]),.dialogbody textarea:not([disabled]),.dialogbody button:not([disabled]),#closeDialog');target?.focus({preventScroll:true});});}}
modal.addEventListener('close',()=>{const target=dialogReturnFocus;dialogReturnFocus=null;if(target?.isConnected)queueMicrotask(()=>target.focus({preventScroll:true}));});
