/* OEE Collaboraction HMI OEE v81 — governed NC parity for Finish PRO and approvals. */
(()=>{
 const clean=v=>String(v??'').trim();
 const num=(form,name)=>{const raw=form?.elements?.[name]?.value;if(raw===''||raw===undefined)return null;const n=Number(raw);return Number.isFinite(n)?n:null;};
 async function policy(){const g=await api('/oee-governance');return {authoritative:g?.authoritative===true,rule:['good_total','good_nc_total'].includes(g?.quality_rule)?g.quality_rule:'good_total',label:g?.quality_rule_label||'Good / Total'};}
 async function finishDialogV81(run){
  let gov;try{gov=await policy();}catch(e){toast('Definisi KPI tidak dapat diverifikasi. Finish PRO ditahan sampai koneksi governance pulih.');return;}
  const unit=clean(run?.unit),ncRequired=gov.authoritative&&gov.rule==='good_nc_total';
  dialog('Finish PRO',`<form id="v81Finish" class="formgrid"><div class="full v40-event-context"><div><span>PRO</span><strong>${esc(run?.pro||'—')}</strong></div><div><span>Target</span><strong>${fmt(Number(run?.planned_qty||0))}${unit?' '+esc(unit):''}</strong></div><div><span>Quality rule</span><strong>${esc(gov.label)}</strong></div><div><span>Governance</span><strong>${gov.authoritative?'Authoritative':'Belum final'}</strong></div></div><label>Actual Qty ${unit?`<small>${esc(unit)}</small>`:''}<input name="actual_qty" type="number" min="0" step="any"><small>Kosong hanya diperbolehkan bila backend memverifikasi counter telemetry authoritative.</small></label><label>Reject Qty ${unit?`<small>${esc(unit)}</small>`:''}<input name="reject_qty" type="number" min="0" step="any" value="0"></label><label>NC Qty ${unit?`<small>${esc(unit)}</small>`:''} ${ncRequired?'<span class="v38-required">Wajib sesuai KPI</span>':''}<input name="nc_qty" type="number" min="0" step="any" ${ncRequired?'required':''}><small>${ncRequired?'NC masuk numerator Quality sesuai baseline.':'Isi bila NC dicatat terpisah; kosong tidak akan ditebak sebagai histori NC.'}</small></label><label>Good Qty ${unit?`<small>${esc(unit)}</small>`:''}<input name="good_qty" type="number" min="0" step="any"><small>Kosong = Actual - Reject - NC bila Actual dapat ditentukan.</small></label><div class="full v40-balance" id="v81FinishBalance"></div><div class="full v40-note">Finish PRO menyimpan snapshot rule Quality yang berlaku saat transaksi ditutup. Perubahan baseline di masa depan tidak mengubah arti transaksi historis.</div><button class="primary full" id="v81FinishSave">Finish & Kirim Verifikasi</button></form>`);
  const form=$('#v81Finish'),balance=$('#v81FinishBalance'),save=$('#v81FinishSave');
  const draw=()=>{const actual=num(form,'actual_qty'),reject=num(form,'reject_qty')??0,nc=num(form,'nc_qty'),good=num(form,'good_qty'),ncEffective=nc??0;let valid=reject>=0&&Number.isFinite(reject);if(nc!==null)valid=valid&&nc>=0;if(good!==null)valid=valid&&good>=0;if(actual!==null)valid=valid&&actual>=0&&(good===null||good+ncEffective+reject<=actual+1e-9);if(ncRequired&&nc===null)valid=false;const autoGood=actual!==null?Math.max(0,actual-reject-ncEffective):null,classified=actual!==null&&good!==null?actual-good-reject-ncEffective:null;balance.className='full v40-balance '+(valid?'ok':'bad');balance.innerHTML=`<span>Konsistensi hasil</span><strong>${!valid?(ncRequired&&nc===null?'NC wajib diisi sesuai Quality rule authoritative.':'Good + NC + Reject tidak boleh melebihi Actual Qty.'):actual===null?'Actual akan diverifikasi backend dari counter; masukkan manual bila telemetry tidak authoritative.':good===null?`Good otomatis = ${fmt(autoGood)}${unit?' '+esc(unit):''}`:`Good ${fmt(good)} + NC ${fmt(ncEffective)} + Reject ${fmt(reject)}${classified>0?` · belum diklasifikasi ${fmt(classified)}`:''} =/≤ Actual ${fmt(actual)}${unit?' '+esc(unit):''}`}</strong>`;save.disabled=!valid;};
  ['actual_qty','reject_qty','nc_qty','good_qty'].forEach(k=>form.elements[k].addEventListener('input',draw));draw();
  form.onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(form));for(const k of ['actual_qty','good_qty','nc_qty'])if(b[k]==='')delete b[k];b.run_id=run.id;try{const r=await api('/shopfloor/finish','POST',b);modal.close();const ncText=r.nc_qty===null||r.nc_qty===undefined?'NC legacy/tidak dicatat':`NC ${fmt(Number(r.nc_qty))}${unit?' '+unit:''}`;toast(`PRO selesai · Actual ${fmt(r.actual_qty)}${unit?' '+unit:''} · Good ${fmt(r.good_qty)}${unit?' '+unit:''} · ${ncText} · menunggu verifikasi`);shopfloor();}catch(err){toast(err.message);}};
 }
 finishDialog=finishDialogV81;
 function appendApprovalContext(tr,a){if(!tr||tr.dataset.v81)return;tr.dataset.v81='1';if(a?.entity_type!=='production_run')return;const e=a.entity||{},cell=tr.children[3];if(!cell)return;const unit=clean(e.unit),u=unit?' '+unit:'',nc=e.nc_qty===null||e.nc_qty===undefined?'—':fmt(Number(e.nc_qty))+u,rule=e.quality_rule_label||'Rule legacy tidak tersimpan',complete=e.classification_complete===true?'Klasifikasi lengkap':'Klasifikasi belum lengkap / legacy';const small=document.createElement('small');small.className='v81-approval-oee';small.textContent=`NC ${nc} · ${rule} · ${complete}${e.governance_approved?' · authoritative':' · non-authoritative'}`;cell.append(small);}
 async function decorateApprovals(){if(view!=='approvals')return;let data;try{data=await api('/approvals');}catch{return;}const pending=(data.rows||[]).filter(x=>x.status==='PENDING'),history=(data.rows||[]).filter(x=>x.status!=='PENDING').slice(0,100),tables=[...document.querySelectorAll('#content section.panel table.release-table')];const groups=[pending,history];tables.slice(0,2).forEach((table,ti)=>{const trs=[...table.querySelectorAll('tbody tr')],items=groups[ti]||[];trs.forEach((tr,i)=>appendApprovalContext(tr,items[i]));});}
 const baseRenderV81=render;render=async function(...args){const out=await baseRenderV81(...args);if(view==='approvals')queueMicrotask(decorateApprovals);return out;};
 window.HMIOeeV81={finishDialog:finishDialogV81,decorateApprovals,policy};
})();
