(()=>{
const token=sessionStorage.getItem('oee-token')||'';
const API=location.hostname.endsWith('workers.dev')?location.origin:'https://oee-collaboraction.offsetbmj.workers.dev';
const EXPECTED=3156,BATCH=5;
const $=s=>document.querySelector(s),logEl=$('#log'),statusEl=$('#status'),bar=$('#bar'),fileEl=$('#file'),start=$('#start'),stats=$('#stats');
const log=(m,c='')=>{const line=document.createElement('div');line.textContent=m;if(c)line.className=c;logEl.appendChild(line);logEl.scrollTop=logEl.scrollHeight;};
async function call(path,method='GET',body){const r=await fetch(API+path,{method,headers:{'Authorization':'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||d.message||('HTTP '+r.status));return d;}
async function refresh(){try{const d=await call('/api/admin/import/status');const vals={sources:d.sources,sheets:d.sheets,documents:d.documents,entries:d.entries,record_chunks:d.record_chunks,source_files:d.source_files,source_file_chunks:d.source_file_chunks};stats.innerHTML=Object.entries(vals).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${Number(v||0).toLocaleString('id-ID')}</b></div>`).join('');return d;}catch(e){stats.innerHTML=`<div class="err">${e.message}</div>`;if(!token)log('Session superadmin tidak ditemukan. Login ke aplikasi worker.dev terlebih dahulu.','err');throw e;}}
function streamFor(file){let s=file.stream();if(/\.gz$/i.test(file.name)){if(!('DecompressionStream'in window))throw new Error('Browser ini tidak mendukung decompression gzip. Gunakan Chrome/Edge terbaru.');s=s.pipeThrough(new DecompressionStream('gzip'));}return s.pipeThrough(new TextDecoderStream());}
async function sendBatch(batch,total){if(!batch.length)return total;const d=await call('/api/admin/import/batch','POST',{statements:batch});total+=d.executed||batch.length;const pct=Math.min(99,(total/EXPECTED)*100);bar.style.width=pct+'%';statusEl.textContent=`${total.toLocaleString('id-ID')} statement berhasil dikirim${EXPECTED?' · sekitar '+pct.toFixed(1)+'%':''}`;if(total%100<batch.length)log(`Imported ${total.toLocaleString('id-ID')} statement…`);return total;}
async function run(file){start.disabled=true;fileEl.disabled=true;bar.style.width='1%';log(`Mulai membaca ${file.name} (${(file.size/1024/1024).toFixed(1)} MB)…`);let reader,buf='',inQuote=false,total=0,batch=[];try{reader=streamFor(file).getReader();while(true){const {value,done}=await reader.read();if(done)break;for(let i=0;i<value.length;i++){const c=value[i];if(c==="'")inQuote=!inQuote;if(c===';'&&!inQuote){const st=buf.trim();buf='';if(st){batch.push(st);if(batch.length>=BATCH){total=await sendBatch(batch,total);batch=[];}}}else buf+=c;}}const tail=buf.trim();if(tail)batch.push(tail);total=await sendBatch(batch,total);bar.style.width='100%';statusEl.textContent=`Import selesai · ${total.toLocaleString('id-ID')} statement diproses`;log(`IMPORT SELESAI · ${total.toLocaleString('id-ID')} statement.`,`ok`);const d=await refresh();log(`D1: sources=${d.sources}, sheets=${d.sheets}, entries=${d.entries}, record_chunks=${d.record_chunks}, source_files=${d.source_files}, source_file_chunks=${d.source_file_chunks}`,'ok');}catch(e){statusEl.textContent='Import berhenti: '+e.message;log('ERROR: '+e.message,'err');start.disabled=false;fileEl.disabled=false;}}
fileEl.addEventListener('change',()=>{const f=fileEl.files[0];start.disabled=!f;statusEl.textContent=f?`${f.name} siap diimport.`:'Menunggu file…';});
start.addEventListener('click',()=>{const f=fileEl.files[0];if(f&&confirm('Import data historis ke D1 production sekarang?'))run(f);});
refresh().catch(()=>{});
})();
