name = "oee-collaboraction"
main = "backend/worker-v6.mjs"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://juldigi0107.github.io,https://oee-collaboraction.offsetbmj.workers.dev"

[assets]
directory = "frontend"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "oee-collaboraction"
database_id = "85624616-87c2-45d4-a4cf-49c0544e163a"

[triggers]
crons = ["* * * * *"]
